NUMBER = "NUMBER"
STRING = "STRING"
FLOAT = "FLOAT"

PLUS = "PLUS"
MINUS = "MINUS"
MULTIPLY = "MULTIPLY"
DIVIDE = "DIVIDE"

LPAREN = "LPAREN"
RPAREN = "RPAREN"

IDENTIFIER = "IDENTIFIER"
EQUALS = "EQUALS"

NEWLINE = "NEWLINE"
COMMA = "COMMA"

COMPARE_GREATER = "COMPARE_GREATER"
COMPARE_LESS = "COMPARE_LESS"
COMPARE_EQUALS = "COMPARE_EQUALS"
COMPARE_NOTEQUALS = "COMPARE_NOTEQUALS"
COMPARE_GREATEREQUAL = "COMPARE_GREATEREQUAL"
COMPARE_LESSEQUAL = "COMPARE_LESSEQUAL"

IF = "IF"
ELIF = "ELIF"
ELSE = "ELSE"
WHILE = "WHILE"
FOR = "FOR"

SEMICOLON = "SEMICOLON"
DECIMALPOINT = "DECIMALPOINT"

LBRACE = "LBRACE"
RBRACE = "RBRACE"

FN = "FN"

TRUE = "TRUE"
FALSE = "FALSE"

LBRACKET = "LBRACKET"
RBRACKET = "RBRACKET"

APPEND = "APPEND"

EOF = "EOF"

LIST_START = "LIST_START"
LIST_END = "LIST_END"
INDEX_ACCESS = "INDEX_ACCESS"


MODULO = "MODULO"
EXPONENT = "EXPONENT"



class Token:
    def __init__(self, type_, value=None):
        self.type = type_
        self.value = value

    def __repr__(self):
        return f"{self.type}:{self.value}"